name: Autograding Tests
on:
  - push
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run setup script
        run: pipx install tko && python .config/grade.py test -o ~/awarded.txt
      - name: Upload evaluation report
        uses: actions/upload-artifact@v4
        with:
          name: awarded
          path: ~/awarded.txt

  run-autograding-tests:
    needs: setup-environment
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    strategy:
      matrix:
        grade: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    name: Grade ${{ matrix.grade }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Load evaluation report
        uses: actions/download-artifact@v4
        with:
          name: awarded
          path: ~/
      - name: Grade Test ${{ matrix.grade }}
        id: grade
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: G${{ matrix.grade }}
          setup-command: ''
          command: '[ "$(cat ~/awarded.txt)" -ge ${{ matrix.grade }} ]'
          timeout: 5
          max-score: 1
      - name: Save result
        run: |
          VAR_NAME=G$(printf "%02d" ${{ matrix.grade }})_RESULTS
          echo "$VAR_NAME=${{ steps.grade.outputs.result }}" >> $GITHUB_ENV

  report:
    needs: run-autograding-tests
    runs-on: ubuntu-latest
    steps:
      - name: Generate report (manual aggregation)
        run: echo "Generating report..."
      - name: Dummy reporter (não é automático com matrix)
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          G01_RESULTS: ${{ env.G01_RESULTS }}
          G02_RESULTS: ${{ env.G02_RESULTS }}
          G03_RESULTS: ${{ env.G03_RESULTS }}
          G04_RESULTS: ${{ env.G04_RESULTS }}
          G05_RESULTS: ${{ env.G05_RESULTS }}
          G06_RESULTS: ${{ env.G06_RESULTS }}
          G07_RESULTS: ${{ env.G07_RESULTS }}
          G08_RESULTS: ${{ env.G08_RESULTS }}
          G09_RESULTS: ${{ env.G09_RESULTS }}
          G10_RESULTS: ${{ env.G10_RESULTS }}
          G11_RESULTS: ${{ env.G11_RESULTS }}
          G12_RESULTS: ${{ env.G12_RESULTS }}
          G13_RESULTS: ${{ env.G13_RESULTS }}
          G14_RESULTS: ${{ env.G14_RESULTS }}
          G15_RESULTS: ${{ env.G15_RESULTS }}
          G16_RESULTS: ${{ env.G16_RESULTS }}
          G17_RESULTS: ${{ env.G17_RESULTS }}
          G18_RESULTS: ${{ env.G18_RESULTS }}
          G19_RESULTS: ${{ env.G19_RESULTS }}
          G20_RESULTS: ${{ env.G20_RESULTS }}
        with:
          runners: G01,G02,G03,G04,G05,G06,G07,G08,G09,G10,G11,G12,G13,G14,G15,G16,G17,G18,G19,G20