name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: grade-01
      id: grade-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-01
        setup-command: ''
        command: grade.py
        input: '1'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-02
      id: grade-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-02
        setup-command: ''
        command: grade.py
        input: '2'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-03
      id: grade-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-03
        setup-command: ''
        command: grade.py
        input: '3'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-04
      id: grade-04
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-04
        setup-command: ''
        command: grade.py
        input: '4'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-05
      id: grade-05
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-05
        setup-command: ''
        command: grade.py
        input: '5'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-06
      id: grade-06
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-06
        setup-command: ''
        command: grade.py
        input: '6'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-07
      id: grade-07
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-07
        setup-command: ''
        command: grade.py
        input: '7'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-08
      id: grade-08
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-08
        setup-command: ''
        command: grade.py
        input: '8'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-09
      id: grade-09
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-09
        setup-command: ''
        command: grade.py
        input: '9'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-10
      id: grade-10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-10
        setup-command: ''
        command: grade.py
        input: '10'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-11
      id: grade-11
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-11
        setup-command: ''
        command: grade.py
        input: '11'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-12
      id: grade-12
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-12
        setup-command: ''
        command: grade.py
        input: '12'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-13
      id: grade-13
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-13
        setup-command: ''
        command: grade.py
        input: '13'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-14
      id: grade-14
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-14
        setup-command: ''
        command: grade.py
        input: '14'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-15
      id: grade-15
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-15
        setup-command: ''
        command: grade.py
        input: '15'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-16
      id: grade-16
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-16
        setup-command: ''
        command: grade.py
        input: '16'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-17
      id: grade-17
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-17
        setup-command: ''
        command: grade.py
        input: '17'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-18
      id: grade-18
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-18
        setup-command: ''
        command: grade.py
        input: '18'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-19
      id: grade-19
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-19
        setup-command: ''
        command: grade.py
        input: '19'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: grade-20
      id: grade-20
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade-20
        setup-command: ''
        command: grade.py
        input: '20'
        expected-output: '1'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRADE-01_RESULTS: "${{steps.grade-01.outputs.result}}"
        GRADE-02_RESULTS: "${{steps.grade-02.outputs.result}}"
        GRADE-03_RESULTS: "${{steps.grade-03.outputs.result}}"
        GRADE-04_RESULTS: "${{steps.grade-04.outputs.result}}"
        GRADE-05_RESULTS: "${{steps.grade-05.outputs.result}}"
        GRADE-06_RESULTS: "${{steps.grade-06.outputs.result}}"
        GRADE-07_RESULTS: "${{steps.grade-07.outputs.result}}"
        GRADE-08_RESULTS: "${{steps.grade-08.outputs.result}}"
        GRADE-09_RESULTS: "${{steps.grade-09.outputs.result}}"
        GRADE-10_RESULTS: "${{steps.grade-10.outputs.result}}"
        GRADE-11_RESULTS: "${{steps.grade-11.outputs.result}}"
        GRADE-12_RESULTS: "${{steps.grade-12.outputs.result}}"
        GRADE-13_RESULTS: "${{steps.grade-13.outputs.result}}"
        GRADE-14_RESULTS: "${{steps.grade-14.outputs.result}}"
        GRADE-15_RESULTS: "${{steps.grade-15.outputs.result}}"
        GRADE-16_RESULTS: "${{steps.grade-16.outputs.result}}"
        GRADE-17_RESULTS: "${{steps.grade-17.outputs.result}}"
        GRADE-18_RESULTS: "${{steps.grade-18.outputs.result}}"
        GRADE-19_RESULTS: "${{steps.grade-19.outputs.result}}"
        GRADE-20_RESULTS: "${{steps.grade-20.outputs.result}}"
      with:
        runners: grade-01,grade-02,grade-03,grade-04,grade-05,grade-06,grade-07,grade-08,grade-09,grade-10,grade-11,grade-12,grade-13,grade-14,grade-15,grade-16,grade-17,grade-18,grade-19,grade-20