name: Autograding Tests
on:
- push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  setup-environment: # Novo job de configuração
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run setup script
      run: pipx install tko && python .config/grade.py test -o ~/awarded.txt
    - name: Upload evaluation report
      uses: actions/upload-artifact@v4 # Usa a action para upload de artefatos
      with:
        name: awarded
        path: ~/awarded.txt
  run-autograding-tests:
    needs: setup-environment
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Load evaluation report
      uses: actions/download-artifact@v4
      with:
        name: awarded # Deve ser o mesmo nome do artefato que foi UPLOADADO
        path: ~/ # Local onde o artefato será baixado
    - name: grade-01
      id: grade-01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: grade-01
        setup-command: ''
        command: '[ "$(cat ~/awarded.txt)" -gt 0 ]'
        timeout: 5
        max-score: 1
    
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRADE-01_RESULTS: "${{steps.grade-01.outputs.result}}"
      with:
        runners: grade-01