name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validação Tarefa Strings
      id: validacao-tarefa-strings
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Validação Tarefa Strings
        setup-command: ''
        command: npm test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VALIDACAO-TAREFA-STRINGS_RESULTS: "${{steps.validacao-tarefa-strings.outputs.result}}"
      with:
        runners: validacao-tarefa-strings
